import { Example } from 'components/Example'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          css={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <h1
            css={{
              fontSize: 64,
            }}
          >
            Welcome to
            <span
              css={{
                background: '-webkit-linear-gradient(45deg, #ED8936, #48BB78)',
                '-webkit-background-clip': 'text',
                '-webkit-text-fill-color': 'transparent',
                marginLeft: '8px',
              }}
            >
              Next Web App
            </span>
          </h1>
          <p>
            <Example />
          </p>
          <p>
            Get started by editing <code>pages/index.tsx</code>
          </p>

          <div>
            <a href="https://nextjs.org/docs">
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn">
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a href="https://github.com/vercel/next.js/tree/canary/examples">
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}
